version: '3.1'

services:
  php_app:
    build: php_app
    container_name: Php_App
    restart: always
    ports:
      - 80:80   
    networks: 
      - network 
    depends_on: [db]
  db:
    image: mysql
    container_name: MySQL    
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
      - seccomp:unconfined
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}   
      MYSQL_HOST: ${DB_SERVER}  
    networks: 
        - network                   
  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks: 
        - network
    depends_on: [db]
  portainer_app:
    container_name: Portainer
    image: portainer/portainer:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 9000:9000
    networks: 
      - network 
    depends_on: [db, php_app, phpmyadmin]       
networks:
  network:
    driver: bridge 
   
